version: "3.7"

services:
  # app:
  #   image: node:latest
  #   command: sh -c "npm install -g nodemon && yarn dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /bookstore
  #   volumes:
  #     - ./:/bookstore

  postgresql:
    image: postgres:latest
    volumes:
      # - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql:/run/secrets/
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/password.txt
      POSTGRES_USER: admin
